[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/sganis/reqwest"]
git = "https://github.com/sganis/reqwest"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"